export const SET_TIME_IN_STATE = 'SET_TIME_IN_STATE';
export const CREATE_CARDS_LIST = 'CREATE_CARDS_LIST';
export const SET_USER_INFO = 'SET_USER_INFO';
export const CREATE_SCOREBOARD = 'CREATE_SCOREBOARD';
